name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "documentation/**"
  workflow_dispatch:

permissions: 
  contents: write

env:
  GIT_AUTHOR_NAME: Actionbot
  GIT_AUTHOR_EMAIL: actions@github.com

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: documentation
          destination: wiki
          token: ${{ secrets.GITHUB_TOKEN }} # Automatically created token for each action run
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
